[workspace]
authors = ["Bouwe Andela <b.andela@esciencecenter.nl>"]
channels = ["conda-forge"]
name = "parallel-python-xarray-dask-example"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
cartopy = "*"
dask = "*"
distributed = "*"
flox = "*"
gcsfs = "*"
h5netcdf = "*"
jupyterlab = "*"
kerchunk = "*"
matplotlib = "*"
netcdf4 = "*"
obspec_utils = "*"
obstore = "*"
pooch = "*"
py-spy = "*"
pyfive = "*"
python-graphviz = "*"
samply = "*"
scipy = "*"
virtualizarr = "*"
xarray = "*"
zarr = "*"
